### ISSUE TITLE
Plan to support. Net core？

### ISSUE THREAD

**Issue by rustbomber** [meteoinfo/MeteoInfoLib_CSharp#1]
MeteoInfoLib_CSharp Plan to support. Net core ？

**Comment by Yaqiang** [comment]
I have no plan to do it. But it is welcome that anyone willing to do it.

**Comment by memoryfraction** [comment]
> MeteoInfoLib_CSharp Plan to support. Net core？

Have a try at the fork version, upgraded it to .NET 5 By recreating the project, but it still relies on the Windows platform because it relies on System.Windows.Forms library.
https://github.com/memoryfraction/MeteoInfoLib_CSharp

@Yaqiang 感谢您的基础工作， 我在其基础上Fork，并升级到了.NET 5版本，希望能帮助更多的人。如果什么需要我做的，还请告知。

**Comment by Yaqiang** [comment]
Thanks for you work on it! Please consider to commit a PR to this repository.

**Comment by memoryfraction** [comment]
> Thanks for you work on it! Please consider to commit a PR to this repository.

Tried, but got notice "failed to push the branch to the remote repository." Is it related to the repo setting? I can commit in wContour repo

**Comment by Yaqiang** [comment]
I have merged your PR. Thanks for your contribution!
